# Generated by Django 4.2.2 on 2023-06-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageComercial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('sem_contato', 'Sem Contato'), ('contato_feito', 'Contato Feito'), ('identificacao_de_interesse', 'Identificação de Interesse'), ('apresentacao', 'Apresentação'), ('proposta_enviada', 'Proposta Enviada')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StageTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('a_fazer', 'A Fazer'), ('fazendo', 'Fazendo'), ('em_aprovacao', 'Em Aprovação'), ('realizado', 'Realizado')], max_length=100)),
            ],
        ),
    ]
