# Generated by Django 4.2.2 on 2023-06-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagecomercial',
            old_name='name',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='stagetasks',
            old_name='name',
            new_name='stage',
        ),
    ]
