# Generated by Django 4.2.2 on 2023-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_rename_name_stagecomercial_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetasks',
            name='stage',
            field=models.CharField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Em Aprovação'), (4, 'Realizado')], max_length=100),
        ),
    ]
