# Generated by Django 4.2.2 on 2023-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_alter_stagetasks_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecomercial',
            name='stage',
            field=models.CharField(choices=[(1, 'Sem Contato'), (2, 'Contato Feito'), (3, 'Identificação de Interesse'), (4, 'Apresentação'), (5, 'Proposta Enviada')], max_length=100),
        ),
    ]
