# Generated by Django 4.2.2 on 2023-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_alter_stagecomercial_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetasks',
            name='stage',
            field=models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Em Aprovação'), (4, 'Realizado')]),
        ),
    ]
