# Generated by Django 4.2.2 on 2023-06-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('rg', models.IntegerField(blank=True, max_length=30, null=True)),
                ('uf_expedition', models.CharField(blank=True, max_length=5, null=True)),
                ('cpf', models.IntegerField(blank=True, max_length=30, null=True)),
                ('cnpj', models.IntegerField(blank=True, max_length=50, null=True)),
                ('telefone', models.IntegerField(blank=True, max_length=20, null=True)),
                ('celular', models.IntegerField(blank=True, max_length=20, null=True)),
                ('emergency_phone', models.IntegerField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('work_station', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
